### ISSUE TITLE
createPath does not connect some lines in SVG export

### ISSUE THREAD

**Issue by jzting** [mattdesl/canvas-sketch-util#16]
Not sure if this is an issue in canvas-sketch-util or arc implementation in d3-path. See example below:

PNG: 
![2021 02 03-08 41 55-0](https://user-images.githubusercontent.com/1255/106755335-02ea3700-65fc-11eb-917b-8982e9676c9c.png)

SVG: https://svgshare.com/s/Th6

**Comment by mattdesl** [comment]
Hmm that's odd ! Could be due to either. I can look into this but I think I'd need your code — or another test case that shows the same error. 

Also, you could try passing `{ optimize: false }` to the pathsToSVG penplot function, as it might be due to something there.

**Comment by jzting** [comment]
```{ optimize: false }``` didn't seem to work. Thanks for taking a look!

https://gist.github.com/jzting/dbf964cc7d0726d3f032cae1e5a3fa64

**Comment by mattdesl** [comment]
Alright, pretty odd but I think there is some bug with d3-path. Hard to track down exactly what's going on here. 

Instead of using `createPath()` which uses d3 under the hood, you can use my own [arc-to](http://npmjs.com/package/arc-to) module which seems to produce correct results, and which just returns a list of points.

```js
const createArc = require('arc-to');

// ... inside drawArc () ...
  const arc = createArc(center.x, center.y, radius, startAng, endAng, positiveRotation);
  paths.push(arc);
```

**Comment by jzting** [comment]
Thank you so much, Matt. That worked perfectly!
